name = "creator-monitoring-platform"
compatibility_date = "2023-12-01"

# Pages configuration
pages_build_output_dir = "frontend/out"

# Build configuration
[build]
command = "cd frontend && npm install && npm run build"
cwd = "/"

[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"