name = "creator-monitoring-api"
main = "src/index.js"
compatibility_date = "2023-12-01"

[build]
command = "npm install"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }