openapi: 3.0.3
info:
  title: Migration Management API
  description: 数据库迁移管理API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local development

paths:
  /migration/start:
    post:
      summary: 启动数据迁移
      description: 创建迁移任务并开始执行
      operationId: startMigration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrationRequest'
      responses:
        '200':
          description: 迁移任务已创建
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationTask'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: 已有迁移任务正在执行
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /migration/status/{taskId}:
    get:
      summary: 查询迁移状态
      description: 获取迁移任务的执行状态和进度
      operationId: getMigrationStatus
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: 迁移任务ID
      responses:
        '200':
          description: 成功返回迁移状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationStatus'
        '404':
          description: 任务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /migration/rollback/{taskId}:
    post:
      summary: 回滚迁移
      description: 将数据库回滚到迁移前的备份点
      operationId: rollbackMigration
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: 迁移任务ID
      responses:
        '200':
          description: 回滚成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RollbackResult'
        '400':
          description: 无法回滚 (任务未完成或无备份)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MigrationRequest:
      type: object
      properties:
        dryRun:
          type: boolean
          default: false
          description: 是否模拟运行 (不实际修改数据)
        createBackup:
          type: boolean
          default: true
          description: 是否创建备份
        timeout:
          type: integer
          default: 300
          description: 超时时间(秒)
      required: []

    MigrationTask:
      type: object
      properties:
        taskId:
          type: string
          description: 任务ID
        status:
          type: string
          enum: [created, running, completed, failed]
        dryRun:
          type: boolean
        backupPath:
          type: string
          nullable: true
          description: 备份文件路径
        createdAt:
          type: string
          format: date-time

    MigrationStatus:
      type: object
      properties:
        taskId:
          type: string
        status:
          type: string
          enum: [created, running, completed, failed, rolled_back]
        progress:
          type: object
          properties:
            phase:
              type: string
              description: 当前阶段
            percentage:
              type: number
              format: float
              description: 进度百分比 (0-100)
        statistics:
          type: object
          properties:
            totalRecords:
              type: integer
            processedRecords:
              type: integer
            successCount:
              type: integer
            failureCount:
              type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              record:
                type: string
              error:
                type: string
        startedAt:
          type: string
          format: date-time
          nullable: true
        completedAt:
          type: string
          format: date-time
          nullable: true
        duration:
          type: number
          description: 执行时长(秒)
          nullable: true

    RollbackResult:
      type: object
      properties:
        taskId:
          type: string
        success:
          type: boolean
        message:
          type: string
        restoredFrom:
          type: string
          description: 恢复来源 (备份文件路径)
        rolledBackAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          nullable: true
